// File generated by Antigravity (Antigravity template)
// To fully configure Firebase, run: flutterfire configure

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2NnQA6WSs6S87hoHfcVCKZGLU7GghjyA',
    appId: '1:109377705274:web:TEMPLATE', // Replace with your Web App ID
    messagingSenderId: '109377705274',
    projectId: 'vibe-a-thon-bugslayer',
    authDomain: 'vibe-a-thon-bugslayer.firebaseapp.com',
    storageBucket: 'vibe-a-thon-bugslayer.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2NnQA6WSs6S87hoHfcVCKZGLU7GghjyA',
    appId: '1:109377705274:android:469507568175608e662c03',
    messagingSenderId: '109377705274',
    projectId: 'vibe-a-thon-bugslayer',
    storageBucket: 'vibe-a-thon-bugslayer.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2NnQA6WSs6S87hoHfcVCKZGLU7GghjyA',
    appId: '1:109377705274:ios:TEMPLATE', // Replace with your iOS App ID
    messagingSenderId: '109377705274',
    projectId: 'vibe-a-thon-bugslayer',
    storageBucket: 'vibe-a-thon-bugslayer.firebasestorage.app',
    iosBundleId: 'com.example.security_app',
  );
}
